'use strict';
/**
 * Real local St Andrews venues & places — bars, cafes, restaurants,
 * entertainment, shops, the golf courses, and the town's landmarks.
 *
 * These are REAL places with real locations (not sample data), seeded once so
 * the Town page, map and search have a genuine "where to go / what's here"
 * list. Student reviews start at 0 and are added by real users.
 */

const VENUES = [
  /* ------------------------------ bars / nightlife ------------------------------ */
  { name: 'The SA — Students’ Association', category: 'bar', address: '47 High Street, St Andrews', emoji: '🎓',
    description: 'Home of student nightlife — society nights, live music, DJs and the famous kebab night. The beating heart of student social life.',
    website: 'https://www.yourunion.net', lat: 56.3360, lng: -2.8020,
    price: '£', hours: '12:00–01:00 (Fri/Sat till late)',
    vibe: 'Loud, friendly, everything is happening',
    mustTry: 'Kebab Night (the St Andrews institution) and any society open night',
    studentTip: 'Society open nights are where you meet your whole year — go early, it gets packed by 8pm.',
    funFact: 'The kebab night tradition at the SA has been a St Andrews rite of passage for decades.' },
  { name: 'The Vic', category: 'bar', address: '1 Saint Marys Place, St Andrews KY16 9UY', emoji: '🍺',
    description: 'St Andrews’ most famous student pub — live music, cheap and cheerful meals, and a bar that stays busy till late. Hosts the town’s Hogmanay party.',
    website: 'https://vicstandrews.co.uk', lat: 56.3402, lng: -2.7990,
    price: '£', hours: '11:00–01:00 (Fri/Sat till 2:00)',
    vibe: 'The people’s pub — cheap, lively, all ages',
    mustTry: 'The breakfast special and a pint of the local',
    studentTip: 'Weekend live music is usually free to get in — it’s the cheapest gig in town.',
    funFact: 'The Vic has been at the centre of St Andrews student life for generations, and throws one of the town’s biggest Hogmanay parties.' },
  { name: 'The Keys Bar', category: 'bar', address: '87 Market Street, St Andrews KY16 9NX', emoji: '🥃',
    description: 'Traditional pub with an excellent whisky selection and very friendly staff — a favourite for a quiet pint on Market Street.',
    price: '££', hours: '11:00–23:00',
    vibe: 'Cozy, proper, a little special',
    mustTry: 'The whisky flight — their selection is a step above every other bar in town',
    studentTip: 'Quieter than the High Street pubs — good for a break between lectures or a proper chat.',
    funFact: 'Market Street is the old trading heart of the town — the Keys sits right in it.' },
  { name: 'Whey Pat Tavern', category: 'bar', address: '1 Bridge Street, St Andrews KY16 9EX', emoji: '📺',
    description: 'Local sports bar — big screens on all the matches, beer, and a solid traditional pub menu.',
    price: '£', hours: '11:00–23:00',
    vibe: 'Big screens, big noise, full when there’s a match',
    mustTry: 'A pint before a rugby or golf match on the big screens',
    studentTip: 'Match days sell out fast — grab a table early on weekends.',
    funFact: 'Bridge Street is one of the oldest streets in the old town, running down towards the harbour.' },
  { name: 'Molly Malones', category: 'bar', address: '5 Alexandra Place, St Andrews KY16 9XD', emoji: '🍀',
    description: 'Irish pub on Alexandra Place serving cocktails, live music and pub classics.',
    price: '£', hours: '11:00–00:00 (Fri/Sat till 01:00)',
    vibe: 'Irish, warm, live music most weekends',
    mustTry: 'A fresh pint and whatever the band’s setlist says',
    studentTip: 'Check the chalkboard for live music — it’s usually the best free set in town that week.',
    funFact: 'Alexandra Place is one of the pretty little back streets of the old town, just off the main drag.' },
  { name: 'Aikman’s Bar & Bistro', category: 'bar', address: '32 Bell Street, St Andrews KY16 9UX', emoji: '🎶',
    description: 'Bar-bistro near the pier with a stage for regular live music — a well-known spot for a night out.',
    price: '££', hours: '11:00–00:00',
    vibe: 'Music-first, bistro food, pre-dinner drinks',
    mustTry: 'Live music night + a bistro snack from the kitchen',
    studentTip: 'Bell Street is the pre-drinks street — Aikman’s is a classic first stop.',
    funFact: 'It sits within sight of the pier and the west shore — you can walk to the beach in minutes.' },
  { name: 'One Under Bar', category: 'bar', address: 'Rusacks, Pilmour Links, St Andrews KY16 9JQ', emoji: '⛳',
    description: 'Golf-themed bar on the Pilmour links — sport, beer and links views, minutes from the courses.',
    price: '££', hours: '10:00–22:00',
    vibe: 'Golf clubhouse meets links bar',
    mustTry: 'A post-round pint with a view over the Pilmour links',
    studentTip: 'Even if you never play, the views over the links are free and excellent at sunset.',
    funFact: 'Pilmour was once its own little village on the links, now absorbed by the golf resort area.' },
  { name: 'The Monkey Ladder', category: 'bar', address: 'South Street, St Andrews', emoji: '🐒',
    description: 'Traditional old-town pub behind the university — a long-running student favourite with a small, proper bar.',
    price: '£', hours: '11:00–23:00',
    vibe: 'Small, proper, old-town traditional',
    mustTry: 'A classic pint in one of the old-town’s smallest bars',
    studentTip: 'Tucked off the main streets — exactly the kind of place you should find, not look for.',
    funFact: 'South Street runs between the old town and the university — the Monkey Ladder is one of its oldest establishments.' },
  { name: 'The Criterion', category: 'bar', address: 'Bell Street, St Andrews', emoji: '🍺',
    description: 'Historic pub near the pier with a long St Andrews history — pints, pool and old-town regulars.',
    price: '£', hours: '11:00–23:00',
    vibe: 'Historic, relaxed, old-town',
    mustTry: 'A pint on the terrace in summer',
    studentTip: 'Near the pier, so it’s an easy stop before or after a west-shore walk.',
    funFact: 'The Criterion has been part of the Bell Street scene for generations — the street’s oldest name in drinks.' },
  { name: 'Ma Bells Bar', category: 'bar', address: 'Old Course Hotel, 290 West Road, St Andrews', emoji: '🏨',
    description: 'The classic hotel bar in the world-famous Old Course Hotel — the place to watch golfers (and be watched).',
    price: '£££', hours: '10:00–18:00',
    vibe: 'Polished, golf-world famous, a little showy',
    mustTry: 'A pre-dinner drink with a view of the Old Course 18th',
    studentTip: 'Free to stand in — even without a round booked, the 18th green view from the bar is worth it.',
    funFact: 'You genuinely might spot a top-10 golfer in here on an Open week.' },

  /* ---------------------------------- cafes ---------------------------------- */
  { name: 'The Elephant House', category: 'cafe', address: '63 High Street, St Andrews', emoji: '☕',
    description: 'St Andrews’ famous coffeehouse and bookshop — a favourite for students and visitors, right in the old town.',
    price: '£', hours: '08:00–17:00',
    vibe: 'Books, coffee, laptops, second years',
    mustTry: 'A flat white and one of the books on the shelf',
    studentTip: 'Great for a revision base on High Street — go early before the 10am lecture crowd lands.',
    funFact: 'Bookshop-cafe is a national institution — this one is in the middle of the oldest university town in Scotland.' },
  { name: 'The Jigger Inn', category: 'cafe', address: 'West Road, by the Old Course, St Andrews', emoji: '🥐',
    description: 'Relaxed inn and café a short walk from the Old Course — breakfasts, lunch and a cosy bar.',
    price: '££', hours: '07:30–22:00',
    vibe: 'Golf-adjacent, cosy, hungry',
    mustTry: 'The breakfast after a cold walk from the Old Course',
    studentTip: 'If you book a golf round, this is the classic post-round refuel.',
    funFact: 'It’s close enough to the course that Open-week golfers have been spotted here for years.' },
  { name: 'Topping’s Bakery', category: 'cafe', address: 'High Street, St Andrews', emoji: '🥐',
    description: 'The town’s famous bakery — fresh bread, buns, shortbread and cakes straight from the ovens.',
    price: '£', hours: '07:30–18:00',
    vibe: 'Queues, crumbs, happiness',
    mustTry: 'A warm bun and a tin of shortbread',
    studentTip: 'The shortbread is the classic St Andrews souvenir — buy one before it sells out (it sells out).',
    funFact: 'St Andrews shortbread is a proper thing — Topping’s has been part of the town’s baking story for generations.' },
  { name: 'Victoria Café', category: 'cafe', address: 'High Street, St Andrews', emoji: '🍳',
    description: 'Cheap, fast, popular café serving student breakfasts and lunches in the middle of the High Street.',
    price: '£', hours: '07:30–17:00',
    vibe: 'Fast, cheap, full at lunchtime',
    mustTry: 'The big breakfast on a £10 budget',
    studentTip: 'Lunch rush is 12:30–1:15 — go before or after if you want a table.',
    funFact: 'The kind of place where the entire second year of a department ends up in one week.' },

  /* ------------------------------- restaurants ------------------------------- */
  { name: 'The Fife Arms', category: 'restaurant', address: '13 Bell Street, St Andrews', emoji: '🍽️',
    description: 'Elegant town-hotel restaurant, a St Andrews institution since 1820 — fine dining in the heart of the old town.',
    price: '£££', hours: '12:00–22:00',
    vibe: 'Elegant, historic, special occasion',
    mustTry: 'A multi-course dinner for a proper night out',
    studentTip: 'Save it for a treat — the building alone (a 19th-century town hotel) is worth the visit.',
    funFact: 'The Fife Arms has hosted royalty, golfers and statesmen since 1820 — one of the most storied hotels in Scotland.' },
  { name: 'Fairmont St Andrews', category: 'restaurant', address: '290 West Road, St Andrews', emoji: '🍷',
    description: 'Luxury seaside hotel with fine dining and floor-to-ceiling views over the Old Course and the sea.',
    price: '£££', hours: '12:00–22:00',
    vibe: 'Sea views, white tablecloths, big occasion',
    mustTry: 'Dinner with the Old Course out the window',
    studentTip: 'The view is free from the terrace — go for a drink at least once.',
    funFact: 'During Open week it’s the most-wanted table in the town — and the most expensive.' },
  { name: 'The Saltire', category: 'restaurant', address: 'Bell Street, St Andrews', emoji: '🥩',
    description: 'Popular local restaurant on Bell Street — hearty plates and a full bar, busy with locals and students alike.',
    price: '££', hours: '12:00–22:00',
    vibe: 'Busy, friendly, proper food',
    mustTry: 'The steak — it’s the most-ordered plate on the menu',
    studentTip: 'Book ahead on weekends, or be ready to wait — Bell Street dinner time moves fast.',
    funFact: 'It’s the kind of place where the whole town shows up — students, locals, and the occasional golfer.' },

  /* ------------------------------ entertainment ------------------------------ */
  { name: 'The Byre Theatre', category: 'entertainment', address: 'West Street, St Andrews', emoji: '🎭',
    description: 'The university’s historic theatre — drama, dance, comedy and music on a stage that has hosted the great and the geeky.',
    price: '££', hours: 'Evenings',
    vibe: 'Proper theatre, student-priced',
    mustTry: 'A full production this term — check the season listings',
    studentTip: 'Student discounts apply, and society theatre nights are often the best value in town.',
    funFact: 'The Byre has been the university’s stage for generations — some of Scotland’s best actors got their first stage time here.' },
  { name: 'St Andrews Sailing Club', category: 'entertainment', address: 'East Shore, St Andrews', emoji: '⛵',
    description: 'The town’s home of sailing — regattas, club races and the annual coastal regatta on the Bay.',
    price: 'Free to watch', hours: 'Daytime, windy days',
    vibe: 'Wind, spray, serious racing',
    mustTry: 'Watch a regatta from the shore — the coastal regatta is the big one',
    studentTip: 'If you want to try sailing, the club runs taster sessions — St Andrews water is famously lively.',
    funFact: 'The Bay is one of the windiest places in Britain on purpose — that’s why sailors love it.' },
  { name: 'Scottish Tennis Museum', category: 'entertainment', address: 'Marsh Road, St Andrews', emoji: '🎾',
    description: 'Compact museum of the history of tennis — the game was codified in Britain, and St Andrews is part of that story.',
    price: '£', hours: 'Daytime',
    vibe: 'Nostalgic, surprising, family-friendly',
    mustTry: 'The vintage racquets and the old Wimbledon archive',
    studentTip: 'A perfect 45-minute rainy-day stop on the way to the Old Course.',
    funFact: 'Much of tennis’ early history was written in Britain in the 1870s — the museum traces that story.' },

  /* ---------------------------------- shops ---------------------------------- */
  { name: 'Main Street & High Street', category: 'shop', address: 'Main Street / High Street, St Andrews', emoji: '🛍️',
    description: 'The town’s main shopping streets — independent boutiques, bookshops, ice-cream and the famous golf stores.',
    price: 'Free to browse', hours: '09:00–17:30',
    vibe: 'Busy in term time, festive at Christmas',
    mustTry: 'The golf shops and the bookshops — both are a proper St Andrews thing',
    studentTip: 'The High Street is where everyone ends up between lectures — 20 minutes covers the lot.',
    funFact: 'For a town this small, it has an absurd number of golf shops. The rest of the world has taken the hint.' },
  { name: 'The Golf House', category: 'shop', address: 'Bell Street, St Andrews', emoji: '⛳',
    description: 'One of the big-name golf shops in the old town — clubs, balls, links sweaters and Open-week merchandise.',
    price: '£–££££', hours: '09:00–18:00',
    vibe: 'Golfing mecca, links-knit heaven',
    mustTry: 'A links sweater (you will want one after one windy day on the beach)',
    studentTip: 'Open-week gear sells out — but the everyday range is always in stock.',
    funFact: 'Links sweaters were originally made for golfers on these exact courses — St Andrews is where the whole thing started.' },

  /* ---------------------------------- gym ------------------------------------ */
  { name: 'The SA — Students’ Gym', category: 'gym', address: '47 High Street, St Andrews', emoji: '💪',
    description: 'The students’ gym in the SA building — weights, cardio and group classes for students and locals.',
    price: '£', hours: '06:00–23:00',
    vibe: 'Early risers, last-minute panic lifts',
    mustTry: 'A group class — they’re the cheapest way to actually show up',
    studentTip: 'Exam period turns the gym into a stress-relief centre — the 6am slot is the survivors’ slot.',
    funFact: 'The SA building is the student heart of the town — the gym, the bar and the societies all share one address.' },

  /* ---------------------------------- golf ----------------------------------- */
  { name: 'The Old Course', category: 'golf', address: 'The Links, St Andrews', emoji: '⛳',
    description: 'The “Home of Golf” — one of the world’s most famous courses, played since the 1500s and home to The Open. Open to the public.',
    website: 'https://www.st-andrewslinks.com', lat: 56.3394, lng: -2.8013,
    price: '£££ (public rounds)', hours: 'Tee times from early morning',
    vibe: 'Sacred, windy, the original',
    mustTry: 'A public round — book weeks ahead, or at least walk it and stop at Swilcan Bridge',
    studentTip: 'Even if you don’t play, you can walk parts of the course — the 18th green overlooks the sea.',
    funFact: 'The Old Course has hosted The Open more times than any other course in the world — next: 2027.' },
  { name: 'Swilcan Bridge', category: 'golf', address: '17th green, The Old Course, St Andrews', emoji: '🌉',
    description: 'The most photographed bridge in golf — crossing Swilcan Burn by the Old Course 17th green.',
    price: 'Free', hours: 'Always',
    vibe: 'Queues, cameras, history',
    mustTry: 'The photo — everyone gets it, and it’s worth it',
    studentTip: 'Go early in the morning to beat the photo queues and watch the golfers instead.',
    funFact: 'Swilcan Bridge is one of the most photographed spots in all of sport — the bridge itself is from the 1800s.' },
  { name: 'The R&A — Home of Golf Museum', category: 'golf', address: 'Marsh Road, St Andrews', emoji: '🏆',
    description: 'Headquarters of golf’s governing body and a world-class museum of the game’s history, by the Old Course.',
    website: 'https://www.ra.com', lat: 56.3390, lng: -2.8040,
    price: '£', hours: 'Daytime',
    vibe: 'Museum, history, the trophies',
    mustTry: 'The Claret Jug (the Open trophy) and the vintage Open films',
    studentTip: 'Free or cheap entry for students in term time — check the door. 45 minutes is enough.',
    funFact: 'The R&A is one of the governing bodies of world golf — it’s been running the game’s rules for centuries from this town.' },
  { name: 'The New Course', category: 'golf', address: 'West Road, St Andrews', emoji: '⛳',
    description: 'One of the Links Trust courses — a rugged, links test just north of the town.',
    price: '££ (public rounds)', hours: 'Tee times',
    vibe: 'Rough, honest, links-pure',
    mustTry: 'A round when the Old Course is fully booked',
    studentTip: 'Midweek public rounds are dramatically cheaper than the Old Course — same wind, fewer queues.',
    funFact: 'The Links Trust runs several courses around town — together they make St Andrews a golf capital in the literal sense.' },

  /* ------------------------------- landmarks ---------------------------------- */
  { name: 'St Andrews Castle', category: 'landmark', address: 'Castle Rock, West Sands, St Andrews', emoji: '🏰',
    description: 'A dramatic 15th-century castle on Castle Rock — the town’s first fortification, right on the beach.',
    lat: 56.3378, lng: -2.8050,
    price: '£', hours: 'Daytime',
    vibe: 'Ruined, dramatic, tidal',
    mustTry: 'The tunnel under the rock — at high tide the sea rushes in through it',
    studentTip: 'Go at high tide for the sea-in-the-cellar moment, or in summer for the views over West Sands.',
    funFact: 'Cardinal Beaton was killed in this castle in 1546 — one of the great set-pieces of the Scottish Reformation.' },
  { name: 'St Salvator’s Church', category: 'landmark', address: 'High Street, St Andrews', emoji: '⛪',
    description: 'The “Bells of St Salvator” — the university’s church, rung for matriculation, graduations and Hogmanay.',
    lat: 56.3363, lng: -2.8025,
    price: 'Free', hours: 'Services & events',
    vibe: 'Stone, history, bells',
    mustTry: 'Hear the bells rung — watch for the bell-ringing schedule (matri, vacs, Hogmanay)',
    studentTip: 'The bells are a student tradition — ringers are students. If you can, join a practice.',
    funFact: 'The bell-ringing of St Salvator’s is one of the oldest student traditions in the UK.' },
  { name: 'The Quad', category: 'landmark', address: 'High Street, St Andrews', emoji: '🌳',
    description: 'The university’s green quadrangle at the heart of the old town — a classic St Andrews picture.',
    lat: 56.3368, lng: -2.8005,
    price: 'Free', hours: 'Always',
    vibe: 'Grass, lawns, the classic photo',
    mustTry: 'The classic St Andrews selfie with the green behind you',
    studentTip: 'Sunday afternoons = the whole town on the grass. Bring a book, or a rugby ball.',
    funFact: 'The Quad is as much a social space as a university one — for 300+ years it’s been where the town and the university mix.' },
  { name: 'West Sands', category: 'landmark', address: 'West Sands, St Andrews', emoji: '🏖️',
    description: 'The famous sandy beach by the castle and the Old Course — calm water and wide sands.',
    lat: 56.3310, lng: -2.8120,
    price: 'Free', hours: 'Always',
    vibe: 'Wide, calm, sunset-perfect',
    mustTry: 'Sunset — the 18th green looks straight out to sea',
    studentTip: 'Summer weekends get busy, but the sand is wide — there’s always a spot.',
    funFact: 'West Sands sits right by the Old Course’s 18th — golfers have been playing beside this beach for centuries.' },
  { name: 'Saltcoats Beach', category: 'landmark', address: 'Saltcoats, St Andrews', emoji: '🏖️',
    description: 'The town’s main beach — sunbathing, water sports and the long walk to the west shore.',
    lat: 56.3300, lng: -2.8100,
    price: 'Free', hours: 'Always',
    vibe: 'Town beach, kites, sun',
    mustTry: 'The long beach walk from Saltcoats to West Sands (about 30 minutes, pure links coast)',
    studentTip: 'Kitesurfing schools run here in the windier months — St Andrews Bay is famously lively.',
    funFact: 'The coastline between Saltcoats and West Sands is one of the most walkable stretches of coast in Scotland.' },
  { name: 'Tay Park', category: 'landmark', address: 'Tay Park, St Andrews', emoji: '🌲',
    description: 'The town’s big park — sports pitches, playgrounds, a bandstand and a splash of green on the east side.',
    lat: 56.3350, lng: -2.7950,
    price: 'Free', hours: 'Always',
    vibe: 'Dog walks, football, Sunday lunch weather',
    mustTry: 'A walk around the loop — it’s the quickest way to feel like you’ve left town',
    studentTip: 'The pitches host town football on weekends — cheap and loud, very St Andrews.',
    funFact: 'Tay Park is where the town goes when it wants space — it’s one of the greenest spots within the old burgh.' },
  { name: 'Kinnaird Head', category: 'landmark', address: 'Kinnaird Head, St Andrews', emoji: '🌊',
    description: 'A dramatic cliff walk and nature reserve north of the town — seabirds, seals and wide views.',
    lat: 56.3300, lng: -2.8160,
    price: 'Free', hours: 'Always',
    vibe: 'Cliffs, gannets, wind in your hair',
    mustTry: 'The cliff-top walk — gannets diving right overhead',
    studentTip: 'Bring a jacket no matter the forecast — the head gets wind from every direction.',
    funFact: 'Kinnaird Head is a wildlife reserve — it’s one of the best seabird spots within walking distance of a university town.' },
  { name: 'The Pier', category: 'landmark', address: 'West Shore, St Andrews', emoji: '⚓',
    description: 'The old fishing pier on the west shore — the spot for the traditional student Pier Walk.',
    lat: 56.3345, lng: -2.8035,
    price: 'Free', hours: 'Always',
    vibe: 'Salt air, gulls, first-years',
    mustTry: 'The Pier Walk — walk out to the end and back (a St Andrews tradition)',
    studentTip: 'It’s cold at the end of the pier, even in summer. That’s the point.',
    funFact: 'The Pier Walk is a proper first-year tradition — groups of students walk out together, usually right after they arrive.' },
];

function seedVenues() {
  const { db } = require('./db');
  const exists = db.prepare('SELECT id FROM places WHERE name = ?');
  const ins = db.prepare(`
    INSERT INTO places (name, category, address, hours, website, description, rating, review_count, emoji, image, lat, lng,
                        price, vibe, must_try, student_tip, fun_fact, is_demo)
    VALUES (?, ?, ?, ?, ?, ?, 0, 0, ?, NULL, ?, ?, ?, ?, ?, ?, ?, 0)
  `);
  let added = 0;
  for (const v of VENUES) {
    if (exists.get(v.name)) continue;
    ins.run(v.name, v.category, v.address, v.hours || null, v.website || null, v.description, v.emoji,
      v.lat ?? null, v.lng ?? null, v.price || null, v.vibe || null, v.mustTry || null, v.studentTip || null, v.funFact || null);
    added++;
  }
  if (added) console.log(`[venues] added ${added} real local venues`);
}

module.exports = { seedVenues, VENUES };
